version: '2.3'

services:
  main:
    container_name: grad_etri
    ipc: host
    shm_size: 256g  
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    env_file:
      - docker-compose-env/main.env
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - type: volume
        source: nfs_shared
        target: /nfs_shared
        volume:
          nocopy: true
      - "/home/mmlab/hdd/grad/sscd/sscd/:/user"
      - "/home/mmlab/hdd/dataset:/dataset"
    ports:
      - "31400:8000"
      - "31402:22"
    expose:
      - "8080"

volumes:
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"

